# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directmessaging', '0001_initial'),
        ('forms', '0002_auto_20160418_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Country', models.CharField(blank=True, max_length=20)),
                ('Website', models.URLField(blank=True, default='')),
                ('Email', models.EmailField(blank=True, default='', max_length=254)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Charity',
                'verbose_name_plural': 'Charities',
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='Charity_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery', models.IntegerField(blank=True, default=0)),
                ('Financial_health', models.IntegerField(blank=True, default=0)),
                ('Strength_of_system', models.IntegerField(blank=True, default=0)),
                ('Progress', models.IntegerField(blank=True, default=0)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMarks',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.Field')),
                ('marks', models.CharField(blank=True, help_text='Enter marks depending on Field Type, seperate with commas', max_length=1000)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'abstract': False,
            },
            bases=('forms.field',),
        ),
        migrations.CreateModel(
            name='RelatedSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Delivery', 'Delivery'), ('Financial_Health', 'Financial_Health'), ('Strength_of_system', 'Strength_of_system'), ('Progress', 'Progress')], max_length=1)),
                ('Number_of_questions', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='directmessaging.Message')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
            ],
            bases=('directmessaging.message',),
        ),
    ]
