# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity_details',
            name='Delivery',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charity_details',
            name='Financial_health',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charity_details',
            name='Progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charity_details',
            name='Strength_of_system',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
