# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160418_0120'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMarks',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.Field')),
                ('marks', models.CharField(blank=True, help_text='Enter marks depending on Field Type, seperate with commas', max_length=1000)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'abstract': False,
            },
            bases=('forms.field',),
        ),
    ]
