# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_relatedsurvey_number_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveymessage',
            name='message_ptr',
        ),
        migrations.RemoveField(
            model_name='surveymessage',
            name='survey',
        ),
        migrations.DeleteModel(
            name='SurveyMessage',
        ),
    ]
